### ISSUE TITLE
找不到fcitx-zh-hant.gram

### ISSUE THREAD

**Issue by spew8712** [expoli/rime-moran-sc#1]
语言模型用法.txt中提到有繁体fcitx模型  fcitx-zh-hant，但在庫中找不到，是否可以提供？謝謝！

**Comment by expoli** [comment]
> 语言模型用法.txt中提到有繁体fcitx模型 fcitx-zh-hant，但在庫中找不到，是否可以提供？謝謝！

你进 qq 群吧，群文件里面也有
[fcitx-zh-hant.zip](https://github.com/user-attachments/files/16634973/fcitx-zh-hant.zip)
